schema: src/lib/gql/graphql.schema.json
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://graphql-pokemon2.vercel.app/
      headers:
        user-agent: JS GraphQL
      introspect: false
